export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const USER_ROUTE = '/user'
export const RECIPIENT_ROUTE = '/recipient'
export const PARTICIPANT_ROUTE = '/participant'